version: '2.1'

services:
  fastify-rest-api:
    image: fastify-rest-api
    build: .
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000
    depends_on:
      - mongodb

   mongodb:
    image: mongo
    container_name: "mongodb"
    environment:
          - MONGO_DATA_DIR=/data/db
          - MONGO_LOG_DIR=/dev/null
    volumes:
          - ./data/db:/data/db
    ports:
            - 27017:27017